/**
 * SPICE Netlist Generator
 * Converts CircuitJson to ngspice-compatible netlist format
 */
import type { CircuitJson, Component, Net } from '../types/circuit';
import type { AnalysisConfig } from '../types/analysis';
import { SPICE_PREFIXES } from '../types/circuit';
import { analysisToSpice } from '../types/analysis';
import { sanitizeNodeName, validateIncludePaths } from './sanitizer';

/**
 * Netlist generation options
 */
export interface NetlistOptions {
    title?: string;
    probes?: string[];
    includeFiles?: string[];
    outputFormat?: 'csv' | 'raw';
    jobDir?: string; // For include path validation
}

/**
 * Default diode model for circuits without explicit model
 */
const DEFAULT_DIODE_MODEL = `.model DDEFAULT D(IS=1e-14 N=1.05 RS=10 BV=100 IBV=1e-10)`;

/**
 * Generate a complete SPICE netlist from circuit JSON
 */
export function generateNetlist(
    circuit: CircuitJson,
    analysis: AnalysisConfig,
    options: NetlistOptions = {},
): string {
    const lines: string[] = [];

    // Title
    const title = options.title || circuit.metadata?.name || 'Untitled Circuit';
    lines.push(`* ${title}`);
    lines.push(`* Generated by eda-core`);
    lines.push(`* ${new Date().toISOString()}`);
    lines.push('');

    // Build node map
    const nodeMap = buildNodeMap(circuit.nets);

    // Check if we need default diode model
    const needsDiodeModel = circuit.components.some(
        (c) => c.type === 'diode' && !c.model,
    );
    if (needsDiodeModel) {
        lines.push('* Default diode model');
        lines.push(DEFAULT_DIODE_MODEL);
        lines.push('');
    }

    // Include files (with validation)
    if (options.includeFiles && options.includeFiles.length > 0) {
        if (options.jobDir) {
            validateIncludePaths(options.includeFiles, options.jobDir);
        }
        lines.push('* Include files');
        for (const file of options.includeFiles) {
            lines.push(`.include "${file}"`);
        }
        lines.push('');
    }

    // Components
    lines.push('* Components');
    for (const component of circuit.components) {
        const spiceLine = componentToSpice(component, nodeMap);
        if (spiceLine) {
            lines.push(spiceLine);
        }
    }
    lines.push('');

    // Analysis
    lines.push('* Analysis');
    lines.push(analysisToSpice(analysis));
    lines.push('');

    // Control block for output
    const probes = options.probes || generateDefaultProbes(circuit, nodeMap);
    lines.push('* Control block');
    lines.push('.control');
    lines.push('  set filetype=ascii');
    lines.push('  run');

    if (probes.length > 0) {
        const probeList = probes.join(' ');
        lines.push(`  wrdata output.csv ${probeList}`);
    }

    lines.push('  quit');
    lines.push('.endc');
    lines.push('');
    lines.push('.end');

    return lines.join('\n');
}

/**
 * Build a map from net IDs to SPICE node names
 */
function buildNodeMap(nets: Net[]): Map<string, string> {
    const nodeMap = new Map<string, string>();

    for (const net of nets) {
        if (net.isGround) {
            nodeMap.set(net.id, '0');
        } else {
            nodeMap.set(net.id, sanitizeNodeName(net.id));
        }
    }

    return nodeMap;
}

/**
 * Convert a component to a SPICE line
 */
function componentToSpice(
    component: Component,
    nodeMap: Map<string, string>,
): string | null {
    const { type, designator, value, model, pins } = component;

    // Ground is not a real component
    if (type === 'ground') {
        return null;
    }

    const prefix = SPICE_PREFIXES[type];
    if (!prefix) {
        throw new Error(`Unknown component type: ${type}`);
    }

    // Get node names for pins
    const nodes = pins.map((pin) => {
        const node = nodeMap.get(pin.netId);
        if (!node) {
            throw new Error(`Net not found: ${pin.netId} for component ${designator}`);
        }
        return node;
    });

    // Generate SPICE line based on component type
    switch (type) {
        case 'resistor':
        case 'capacitor':
        case 'inductor':
            return `${designator} ${nodes.join(' ')} ${value || '0'}`;

        case 'voltage_source':
        case 'current_source':
            return `${designator} ${nodes.join(' ')} ${value || 'DC 0'}`;

        case 'diode':
            return `${designator} ${nodes.join(' ')} ${model || 'DDEFAULT'}`;

        default:
            throw new Error(`Unsupported component type: ${type}`);
    }
}

/**
 * Generate default probes (all node voltages)
 */
function generateDefaultProbes(
    circuit: CircuitJson,
    nodeMap: Map<string, string>,
): string[] {
    const probes: string[] = [];

    for (const net of circuit.nets) {
        if (!net.isGround) {
            const nodeName = nodeMap.get(net.id);
            if (nodeName) {
                probes.push(`v(${nodeName})`);
            }
        }
    }

    return probes;
}

/**
 * Get all unique node names from a circuit
 */
export function getNodeNames(circuit: CircuitJson): string[] {
    const nodeMap = buildNodeMap(circuit.nets);
    return Array.from(nodeMap.values());
}

/**
 * Validate that a netlist is syntactically correct (basic check)
 */
export function validateNetlist(netlist: string): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    const lines = netlist.split('\n');

    let hasEnd = false;
    let hasAnalysis = false;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i]?.trim() || '';

        // Skip comments and empty lines
        if (line.startsWith('*') || line === '') {
            continue;
        }

        // Check for .end
        if (line.toLowerCase() === '.end') {
            hasEnd = true;
        }

        // Check for analysis
        if (line.toLowerCase().startsWith('.tran') ||
            line.toLowerCase().startsWith('.ac') ||
            line.toLowerCase().startsWith('.dc') ||
            line.toLowerCase().startsWith('.op')) {
            hasAnalysis = true;
        }
    }

    if (!hasEnd) {
        errors.push('Netlist missing .end statement');
    }

    if (!hasAnalysis) {
        errors.push('Netlist missing analysis command (.tran, .ac, .dc, or .op)');
    }

    return {
        valid: errors.length === 0,
        errors,
    };
}