/**
 * SPICE Netlist Generator
 * Converts CircuitJson to ngspice-compatible netlist format
 */
import type { CircuitJson, Component, Net, ModelDef } from '../types/circuit';
import type { AnalysisConfig } from '../types/analysis';
import { SPICE_PREFIXES, COMPONENT_PINS } from '../types/circuit';
import { analysisToSpice } from '../types/analysis';
import { buildZenerModel } from '../models/library';
import { sanitizeNodeName, validateIncludePaths } from './sanitizer';

/**
 * Netlist generation options
 */
export interface NetlistOptions {
    title?: string;
    probes?: string[];
    includeFiles?: string[];
    outputFormat?: 'csv' | 'raw';
    jobDir?: string; // For include path validation
}

/**
 * Default diode model for circuits without explicit model
 */
const DEFAULT_DIODE_MODEL = `.model DDEFAULT D(IS=1e-14 N=1.05 RS=10 BV=100 IBV=1e-10)`;

/**
 * Generate a complete SPICE netlist from circuit JSON
 */
export function generateNetlist(
    circuit: CircuitJson,
    analysis: AnalysisConfig,
    options: NetlistOptions = {},
): string {
    const lines: string[] = [];

    // Title
    const title = options.title || circuit.metadata?.name || 'Untitled Circuit';
    lines.push(`* ${title}`);
    lines.push(`* Generated by eda-core`);
    lines.push(`* ${new Date().toISOString()}`);
    lines.push('');

    // Build node map
    const nodeMap = buildNodeMap(circuit.nets);

    // Track every emitted .model/.subckt name -> body so we (a) dedup identical definitions and
    // (b) refuse to SILENTLY drop a conflicting body that reuses a name (which would emit only the
    // first and simulate the wrong device). The reserved default diode model seeds the map so a
    // caller-supplied 'DDEFAULT' can't produce a duplicate card or shadow the built-in defaults.
    const emittedModels = new Map<string, string>();

    // Check if we need default diode model
    const needsDiodeModel = circuit.components.some(
        (c) => c.type === 'diode' && !c.model,
    );
    if (needsDiodeModel) {
        lines.push('* Default diode model');
        lines.push(DEFAULT_DIODE_MODEL);
        lines.push('');
        emittedModels.set('DDEFAULT', DEFAULT_DIODE_MODEL);
    }

    // Circuit-level model/subckt definitions (active devices reference these by name). Emitted once,
    // before the component lines that reference them. A repeated name with an identical body is a
    // harmless duplicate (dropped); a repeated name with a DIFFERENT body is a hard error.
    if (circuit.models && circuit.models.length > 0) {
        const modelLines: string[] = [];
        for (const m of circuit.models) {
            const existing = emittedModels.get(m.name);
            if (existing !== undefined) {
                if (existing !== m.body) {
                    throw new Error(
                        `Conflicting definitions for model '${m.name}': the same name is defined with two different bodies.`,
                    );
                }
                continue; // identical duplicate — already emitted
            }
            emittedModels.set(m.name, m.body);
            modelLines.push(m.body);
        }
        if (modelLines.length > 0) {
            lines.push('* Models');
            lines.push(...modelLines);
            lines.push('');
        }
    }

    // Zener models: generated parametrically from each zener component's breakdown voltage (`value`),
    // deduped by name (same voltage -> one model) and conflict-checked against everything above.
    const zenerLines: string[] = [];
    for (const c of circuit.components) {
        if (c.type !== 'zener') continue;
        const zm = c.value ? buildZenerModel(c.value) : null;
        if (!zm) continue; // a value-less / unparseable zener is skipped here and flagged by ERC
        const existing = emittedModels.get(zm.name);
        if (existing !== undefined) {
            if (existing !== zm.body) {
                throw new Error(
                    `Conflicting definitions for model '${zm.name}': the same name is defined with two different bodies.`,
                );
            }
            continue;
        }
        emittedModels.set(zm.name, zm.body);
        zenerLines.push(zm.body);
    }
    if (zenerLines.length > 0) {
        lines.push('* Zener models');
        lines.push(...zenerLines);
        lines.push('');
    }

    // Include files (with validation)
    if (options.includeFiles && options.includeFiles.length > 0) {
        if (options.jobDir) {
            validateIncludePaths(options.includeFiles, options.jobDir);
        }
        lines.push('* Include files');
        for (const file of options.includeFiles) {
            lines.push(`.include "${file}"`);
        }
        lines.push('');
    }

    // Components. A model lookup lets subckt instances bind their nodes by pinId (the macromodel's
    // declared port order) instead of trusting the authored pin-array order.
    const modelMap = new Map<string, ModelDef>();
    for (const m of circuit.models ?? []) {
        if (!modelMap.has(m.name)) modelMap.set(m.name, m);
    }
    lines.push('* Components');
    for (const component of circuit.components) {
        const spiceLine = componentToSpice(component, nodeMap, modelMap);
        if (spiceLine) {
            lines.push(spiceLine);
        }
    }
    lines.push('');

    // Analysis
    lines.push('* Analysis');
    lines.push(analysisToSpice(analysis));
    lines.push('');

    // Control block for output
    const probes = options.probes || generateDefaultProbes(circuit, nodeMap);
    lines.push('* Control block');
    lines.push('.control');
    lines.push('  set filetype=ascii');
    lines.push('  run');

    if (probes.length > 0) {
        const probeList = probes.join(' ');
        lines.push(`  wrdata output.csv ${probeList}`);
    }

    lines.push('  quit');
    lines.push('.endc');
    lines.push('');
    lines.push('.end');

    return lines.join('\n');
}

/**
 * Build a map from net IDs to SPICE node names
 */
function buildNodeMap(nets: Net[]): Map<string, string> {
    const nodeMap = new Map<string, string>();

    for (const net of nets) {
        if (net.isGround) {
            nodeMap.set(net.id, '0');
        } else {
            nodeMap.set(net.id, sanitizeNodeName(net.id));
        }
    }

    return nodeMap;
}

/**
 * Convert a component to a SPICE line
 */
function componentToSpice(
    component: Component,
    nodeMap: Map<string, string>,
    modelMap?: Map<string, ModelDef>,
): string | null {
    const { type, designator, value, model, pins } = component;

    // Not emitted to SPICE: `ground` is node 0, `generic` is a catalog-only part with no simulatable
    // model. Both are skipped (not an error) so a circuit can carry real parts that aren't simulatable.
    if (type === 'ground' || type === 'generic') {
        return null;
    }

    // Any type without a SPICE element prefix is non-emittable — skip it gracefully rather than throw,
    // mirroring the parser/ERC which tolerate unknown types (keeps the netlist resilient).
    const prefix = SPICE_PREFIXES[type];
    if (!prefix) {
        return null;
    }

    // Get node names for pins
    const nodes = pins.map((pin) => {
        const node = nodeMap.get(pin.netId);
        if (!node) {
            throw new Error(`Net not found: ${pin.netId} for component ${designator}`);
        }
        return node;
    });

    // Generate SPICE line based on component type
    switch (type) {
        case 'resistor':
        case 'capacitor':
        case 'inductor':
            return `${designator} ${nodes.join(' ')} ${value || '0'}`;

        case 'voltage_source':
        case 'current_source':
            return `${designator} ${nodes.join(' ')} ${value || 'DC 0'}`;

        case 'diode':
            return `${designator} ${nodes.join(' ')} ${model || 'DDEFAULT'}`;

        // A Zener is the SPICE diode device with a breakdown model generated from `value` (the Zener
        // voltage). Nodes are emitted in canonical anode,cathode order (by pinId) so polarity — which
        // is what makes a Zener clamp/regulate — is correct regardless of the authored pin order.
        case 'zener': {
            if (!value) return null;
            const zm = buildZenerModel(value);
            if (!zm) return null;
            return `${designator} ${orderedNodes(component, nodeMap).join(' ')} ${zm.name}`;
        }

        // Active devices are model-based. Nodes are emitted in the canonical pin order (bjt c,b,e /
        // mosfet d,g,s,b / jfet d,g,s) resolved by pinId, NOT by the authored array order. Without a
        // model name the device can't be a valid SPICE line, so skip it (ERC flags MODEL_REQUIRED).
        case 'bjt':
        case 'mosfet':
        case 'jfet': {
            if (!model) return null;
            return `${designator} ${orderedNodes(component, nodeMap).join(' ')} ${model}`;
        }

        // A subcircuit instance (e.g. an op-amp). Variable-arity: nodes are emitted in the AUTHORED pin
        // order, which MUST match the referenced `.subckt` port order (the generator cannot reorder
        // because the port names are macromodel-specific). The SPICE instance line must start with 'X',
        // so one is prefixed when the (schematic) designator doesn't already — e.g. U1 -> XU1.
        case 'subckt': {
            if (!model) return null;
            const inst = /^x/i.test(designator) ? designator : `X${designator}`;
            // Bind nodes by the macromodel's declared port order (pinId) when it's known, so the authored
            // pin-array order is irrelevant and a reordered-but-complete pin set still nets correctly
            // (mirrors bjt/mosfet). Fall back to the authored order for an unknown / user-defined subckt.
            const def = modelMap?.get(model);
            const subcktNodes =
                def?.ports && def.ports.length > 0
                    ? nodesForPinOrder(component, nodeMap, def.ports)
                    : nodes;
            return `${inst} ${subcktNodes.join(' ')} ${model}`;
        }

        default:
            // Forward-compatible: a known-but-non-emittable type is skipped, not fatal.
            return null;
    }
}

/**
 * Resolve a fixed-arity component's nodes in the canonical COMPONENT_PINS order (by pinId), so a BJT
 * always emits `c b e` and a MOSFET `d g s b` regardless of the order pins were authored in.
 */
function orderedNodes(component: Component, nodeMap: Map<string, string>): string[] {
    return nodesForPinOrder(component, nodeMap, COMPONENT_PINS[component.type]);
}

/**
 * Resolve a component's nodes in an explicit pinId order (used for fixed-arity types via COMPONENT_PINS,
 * and for subckt instances via the macromodel's declared port order). Throws if a required pin is absent.
 */
function nodesForPinOrder(
    component: Component,
    nodeMap: Map<string, string>,
    pinIds: string[],
): string[] {
    return pinIds.map((pinId) => {
        const pin = component.pins.find((p) => p.pinId === pinId);
        if (!pin) {
            throw new Error(`Component ${component.designator} (${component.type}) is missing pin '${pinId}'`);
        }
        const node = nodeMap.get(pin.netId);
        if (!node) {
            throw new Error(`Net not found: ${pin.netId} for component ${component.designator}`);
        }
        return node;
    });
}

/**
 * Generate default probes (all node voltages)
 */
function generateDefaultProbes(
    circuit: CircuitJson,
    nodeMap: Map<string, string>,
): string[] {
    const probes: string[] = [];

    for (const net of circuit.nets) {
        if (!net.isGround) {
            const nodeName = nodeMap.get(net.id);
            if (nodeName) {
                probes.push(`v(${nodeName})`);
            }
        }
    }

    return probes;
}

/**
 * Get all unique node names from a circuit
 */
export function getNodeNames(circuit: CircuitJson): string[] {
    const nodeMap = buildNodeMap(circuit.nets);
    return Array.from(nodeMap.values());
}

/**
 * Validate that a netlist is syntactically correct (basic check)
 */
export function validateNetlist(netlist: string): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    const lines = netlist.split('\n');

    let hasEnd = false;
    let hasAnalysis = false;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i]?.trim() || '';

        // Skip comments and empty lines
        if (line.startsWith('*') || line === '') {
            continue;
        }

        // Check for .end
        if (line.toLowerCase() === '.end') {
            hasEnd = true;
        }

        // Check for analysis
        if (line.toLowerCase().startsWith('.tran') ||
            line.toLowerCase().startsWith('.ac') ||
            line.toLowerCase().startsWith('.dc') ||
            line.toLowerCase().startsWith('.op')) {
            hasAnalysis = true;
        }
    }

    if (!hasEnd) {
        errors.push('Netlist missing .end statement');
    }

    if (!hasAnalysis) {
        errors.push('Netlist missing analysis command (.tran, .ac, .dc, or .op)');
    }

    return {
        valid: errors.length === 0,
        errors,
    };
}